// Copyright 2026, COUI contributors
// SPDX-License-Identifier: Apache-2.0

// ---------------------------------------------------------------------------------------
// GENERATED FILE - do not edit by hand.
//
// Source: ColorOS 17.0.0 `com.android.settings` resources.arsc.
//
// The `Theme.COUI.Main` / `Theme.COUI.Main.Dark` style chains were expanded recursively
// (12 levels: Theme.COUI.Main -> Theme.COUI.Blue -> Theme.COUI -> ThemeOverrideBase ->
// Theme.AppCompat.Light -> ...), then every remaining `@color/...` indirection was followed
// to a literal ARGB value. 103 of 103 `coui*` colour attributes resolved
// on both the light and the dark side and are reproduced below.
//
// Values are 8-digit AARRGGBB.
//
// Regenerate with: coui/tools/gen_tokens.py
// ---------------------------------------------------------------------------------------

package io.wfc35286.coui.kmp.token

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * The complete COUI colour palette, transcribed from the ColorOS theme rather than eyeballed.
 *
 * COUI's neutrals are alpha-based (one ink colour at many opacities) instead of a set of
 * distinct greys, which is why so many entries look like the same colour at different alphas.
 */
@Immutable
data class CouiColorTokens(
    /** `couiBtnDefaultTextColorDisable` */
    val couiBtnDefaultTextColorDisable: Color,
    /** `couiBtnDrawableColorDisabled` */
    val couiBtnDrawableColorDisabled: Color,
    /** `couiBtnPartCheckInnerColorOnDisabled` */
    val couiBtnPartCheckInnerColorOnDisabled: Color,
    /** `couiBtnRadioColorOn` */
    val couiBtnRadioColorOn: Color,
    /** `couiBtnSecondaryTextColorDisable` */
    val couiBtnSecondaryTextColorDisable: Color,
    /** `couiColorAdditional` */
    val additional: Color,
    /** `couiColorAiPaymentDialogMessage` */
    val aiPaymentDialogMessage: Color,
    /** `couiColorAiPaymentDialogTitle` */
    val aiPaymentDialogTitle: Color,
    /** `couiColorAiPaymentPrimary` */
    val aiPaymentPrimary: Color,
    /** `couiColorAiPaymentPrimaryDisabled` */
    val aiPaymentPrimaryDisabled: Color,
    /** `couiColorAiPaymentPrimaryText` */
    val aiPaymentPrimaryText: Color,
    /** `couiColorAiPaymentPrimaryTextDisabled` */
    val aiPaymentPrimaryTextDisabled: Color,
    /** `couiColorAiPaymentSecondary` */
    val aiPaymentSecondary: Color,
    /** `couiColorAiPaymentSecondaryDisabled` */
    val aiPaymentSecondaryDisabled: Color,
    /** `couiColorAiPaymentSecondaryText` */
    val aiPaymentSecondaryText: Color,
    /** `couiColorAiPaymentSecondaryTextDisabled` */
    val aiPaymentSecondaryTextDisabled: Color,
    /** `couiColorAssist` */
    val assist: Color,
    /** `couiColorAzure` */
    val azure: Color,
    /** `couiColorAzureVariant` */
    val azureVariant: Color,
    /** `couiColorBackground` */
    val background: Color,
    /** `couiColorBackgroundElevated` */
    val backgroundElevated: Color,
    /** `couiColorBackgroundElevatedWithCard` */
    val backgroundElevatedWithCard: Color,
    /** `couiColorBackgroundTop` */
    val backgroundTop: Color,
    /** `couiColorBackgroundWithCard` */
    val backgroundWithCard: Color,
    /** `couiColorBar` */
    val bar: Color,
    /** `couiColorBlue` */
    val blue: Color,
    /** `couiColorBlueVariant` */
    val blueVariant: Color,
    /** `couiColorBottomBar` */
    val bottomBar: Color,
    /** `couiColorCard` */
    val card: Color,
    /** `couiColorCardBackground` */
    val cardBackground: Color,
    /** `couiColorCardPressed` */
    val cardPressed: Color,
    /** `couiColorContainer12` */
    val container12: Color,
    /** `couiColorContainer16` */
    val container16: Color,
    /** `couiColorContainer4` */
    val container4: Color,
    /** `couiColorContainer8` */
    val container8: Color,
    /** `couiColorContainerAzure` */
    val containerAzure: Color,
    /** `couiColorContainerBlue` */
    val containerBlue: Color,
    /** `couiColorContainerCyan` */
    val containerCyan: Color,
    /** `couiColorContainerGreen` */
    val containerGreen: Color,
    /** `couiColorContainerMint` */
    val containerMint: Color,
    /** `couiColorContainerOrange` */
    val containerOrange: Color,
    /** `couiColorContainerPurple` */
    val containerPurple: Color,
    /** `couiColorContainerRed` */
    val containerRed: Color,
    /** `couiColorContainerSolid` */
    val containerSolid: Color,
    /** `couiColorContainerTheme` */
    val containerTheme: Color,
    /** `couiColorContainerThemeHalftone` */
    val containerThemeHalftone: Color,
    /** `couiColorContainerViolet` */
    val containerViolet: Color,
    /** `couiColorContainerYellow` */
    val containerYellow: Color,
    /** `couiColorControls` */
    val controls: Color,
    /** `couiColorCyan` */
    val cyan: Color,
    /** `couiColorCyanVariant` */
    val cyanVariant: Color,
    /** `couiColorDisable` */
    val disable: Color,
    /** `couiColorDisabledNeutral` */
    val disabledNeutral: Color,
    /** `couiColorDivider` */
    val divider: Color,
    /** `couiColorError` */
    val error: Color,
    /** `couiColorErrorDisabled` */
    val errorDisabled: Color,
    /** `couiColorErrorTextBg` */
    val errorTextBg: Color,
    /** `couiColorFillSolid` */
    val fillSolid: Color,
    /** `couiColorFillThin` */
    val fillThin: Color,
    /** `couiColorFocus` */
    val focus: Color,
    /** `couiColorFocusOutline` */
    val focusOutline: Color,
    /** `couiColorGreen` */
    val green: Color,
    /** `couiColorGreenVariant` */
    val greenVariant: Color,
    /** `couiColorHintNeutral` */
    val hintNeutral: Color,
    /** `couiColorHover` */
    val hover: Color,
    /** `couiColorLabelOnColor` */
    val labelOnColor: Color,
    /** `couiColorLabelPrimary` */
    val labelPrimary: Color,
    /** `couiColorLabelPrimaryVariant` */
    val labelPrimaryVariant: Color,
    /** `couiColorLabelQuaternary` */
    val labelQuaternary: Color,
    /** `couiColorLabelSecondary` */
    val labelSecondary: Color,
    /** `couiColorLabelSecondaryVariant` */
    val labelSecondaryVariant: Color,
    /** `couiColorLabelTertiary` */
    val labelTertiary: Color,
    /** `couiColorLabelTheme` */
    val labelTheme: Color,
    /** `couiColorMask` */
    val mask: Color,
    /** `couiColorMint` */
    val mint: Color,
    /** `couiColorMintVariant` */
    val mintVariant: Color,
    /** `couiColorOnPrimary` */
    val onPrimary: Color,
    /** `couiColorOrange` */
    val orange: Color,
    /** `couiColorOrangeVariant` */
    val orangeVariant: Color,
    /** `couiColorPress` */
    val press: Color,
    /** `couiColorPressBackground` */
    val pressBackground: Color,
    /** `couiColorPrimary` */
    val primary: Color,
    /** `couiColorPrimaryNeutral` */
    val primaryNeutral: Color,
    /** `couiColorPrimaryText` */
    val primaryText: Color,
    /** `couiColorPrimaryTextOnPopup` */
    val primaryTextOnPopup: Color,
    /** `couiColorPurple` */
    val purple: Color,
    /** `couiColorPurpleVariant` */
    val purpleVariant: Color,
    /** `couiColorQuarternaryNeutral` */
    val quarternaryNeutral: Color,
    /** `couiColorRed` */
    val red: Color,
    /** `couiColorRedVariant` */
    val redVariant: Color,
    /** `couiColorRipplePressBackground` */
    val ripplePressBackground: Color,
    /** `couiColorSecondNeutral` */
    val secondNeutral: Color,
    /** `couiColorSecondary` */
    val secondary: Color,
    /** `couiColorSuccess` */
    val success: Color,
    /** `couiColorSurface` */
    val surface: Color,
    /** `couiColorSurfaceTop` */
    val surfaceTop: Color,
    /** `couiColorSurfaceWithCard` */
    val surfaceWithCard: Color,
    /** `couiColorTips` */
    val tips: Color,
    /** `couiColorViolet` */
    val violet: Color,
    /** `couiColorVioletVariant` */
    val violetVariant: Color,
    /** `couiColorYellow` */
    val yellow: Color,
    /** `couiColorYellowVariant` */
    val yellowVariant: Color,
    /** `couiPrimaryTextColor` */
    val couiPrimaryTextColor: Color,
) {
    companion object {
        /** `Theme.COUI.Main` */
        val Light: CouiColorTokens = CouiColorTokens(
            couiBtnDefaultTextColorDisable = Color(0x8AFFFFFF),
            couiBtnDrawableColorDisabled = Color(0x14000000),
            couiBtnPartCheckInnerColorOnDisabled = Color(0xFFFAFAFA),
            couiBtnRadioColorOn = Color(0x8AFFFFFF),
            couiBtnSecondaryTextColorDisable = Color(0x42000000),
            additional = Color(0xFF0080FF),
            aiPaymentDialogMessage = Color(0xE6000000),
            aiPaymentDialogTitle = Color(0xE6000000),
            aiPaymentPrimary = Color(0xFF001D38),
            aiPaymentPrimaryDisabled = Color(0x4D001D38),
            aiPaymentPrimaryText = Color(0xFFFFFFFF),
            aiPaymentPrimaryTextDisabled = Color(0x8AFFFFFF),
            aiPaymentSecondary = Color(0x14000000),
            aiPaymentSecondaryDisabled = Color(0x14000000),
            aiPaymentSecondaryText = Color(0xE6000000),
            aiPaymentSecondaryTextDisabled = Color(0x42000000),
            assist = Color(0xFF5C93E5),
            azure = Color(0xFF00A1FF),
            azureVariant = Color(0xFF45ABE5),
            background = Color(0xFFFFFFFF),
            backgroundElevated = Color(0xFFFFFFFF),
            backgroundElevatedWithCard = Color(0xFFF0F1F2),
            backgroundTop = Color(0xFFFFFFFF),
            backgroundWithCard = Color(0xFFF0F1F2),
            bar = Color(0xFFFAFAFA),
            blue = Color(0xFF0080FF),
            blueVariant = Color(0xFF5C93E5),
            bottomBar = Color(0xFFFAFAFA),
            card = Color(0xFFFFFFFF),
            cardBackground = Color(0xFFFFFFFF),
            cardPressed = Color(0xFFE6E6E6),
            container12 = Color(0x1F000000),
            container16 = Color(0x29000000),
            container4 = Color(0x0A000000),
            container8 = Color(0x14000000),
            containerAzure = Color(0xFFCEE5EB),
            containerBlue = Color(0xFFC9DAE4),
            containerCyan = Color(0xFFBEDADD),
            containerGreen = Color(0xFFBADECA),
            containerMint = Color(0xFFBADEDB),
            containerOrange = Color(0xFFFAE7D6),
            containerPurple = Color(0xFFE0D6EB),
            containerRed = Color(0xFFEEDADC),
            containerSolid = Color(0xFFEBEBEB),
            containerTheme = Color(0xFF0080FF),
            containerThemeHalftone = Color(0x260080FF),
            containerViolet = Color(0xFFD6D5EE),
            containerYellow = Color(0xFFF6E7C6),
            controls = Color(0x29000000),
            cyan = Color(0xFF1DBACC),
            cyanVariant = Color(0xFF39AFBD),
            disable = Color(0x4D0080FF),
            disabledNeutral = Color(0x42000000),
            divider = Color(0x1F000000),
            error = Color(0xFFDB382C),
            errorDisabled = Color(0x4DDB382C),
            errorTextBg = Color(0x4DE82A18),
            fillSolid = Color(0xFFEBEBEB),
            fillThin = Color(0x0A000000),
            focus = Color(0x1F0080FF),
            focusOutline = Color(0x660080FF),
            green = Color(0xFF00BD13),
            greenVariant = Color(0xFF4BBD57),
            hintNeutral = Color(0x42000000),
            hover = Color(0x14000000),
            labelOnColor = Color(0xFFFFFFFF),
            labelPrimary = Color(0xE6000000),
            labelPrimaryVariant = Color(0xB8000000),
            labelQuaternary = Color(0x14000000),
            labelSecondary = Color(0x8A000000),
            labelSecondaryVariant = Color(0x66000000),
            labelTertiary = Color(0x42000000),
            labelTheme = Color(0xFF0080FF),
            mask = Color(0x33000000),
            mint = Color(0xFF00CC88),
            mintVariant = Color(0xFF39BD91),
            onPrimary = Color(0xFFFFFFFF),
            orange = Color(0xFFFF7700),
            orangeVariant = Color(0xFFE58F45),
            press = Color(0x1F000000),
            pressBackground = Color(0x14000000),
            primary = Color(0xFF0080FF),
            primaryNeutral = Color(0xE6000000),
            primaryText = Color(0xFF0080FF),
            primaryTextOnPopup = Color(0xFF0080FF),
            purple = Color(0xFFA723FF),
            purpleVariant = Color(0xFFB873E5),
            quarternaryNeutral = Color(0x14000000),
            red = Color(0xFFEB3B2F),
            redVariant = Color(0xFFE56E65),
            ripplePressBackground = Color(0x99B4B4B4),
            secondNeutral = Color(0x8A000000),
            secondary = Color(0x260080FF),
            success = Color(0xFF00BD13),
            surface = Color(0xFFFFFFFF),
            surfaceTop = Color(0xFFFFFFFF),
            surfaceWithCard = Color(0xFFF0F1F2),
            tips = Color(0xFF0080FF),
            violet = Color(0xFF5A47FF),
            violetVariant = Color(0xFF7E73E5),
            yellow = Color(0xFFFFB200),
            yellowVariant = Color(0xFFE5AF2E),
            couiPrimaryTextColor = Color(0xFF000000),
        )

        /** `Theme.COUI.Main.Dark` */
        val Dark: CouiColorTokens = CouiColorTokens(
            couiBtnDefaultTextColorDisable = Color(0x28FFFFFF),
            couiBtnDrawableColorDisabled = Color(0x26FFFFFF),
            couiBtnPartCheckInnerColorOnDisabled = Color(0xFF050505),
            couiBtnRadioColorOn = Color(0xFF050505),
            couiBtnSecondaryTextColorDisable = Color(0x28FFFFFF),
            additional = Color(0xFF1A8CFF),
            aiPaymentDialogMessage = Color(0xE6FFFFFF),
            aiPaymentDialogTitle = Color(0xE6FFFFFF),
            aiPaymentPrimary = Color(0xFFDCE7FF),
            aiPaymentPrimaryDisabled = Color(0x4DDCE7FF),
            aiPaymentPrimaryText = Color(0xE6000000),
            aiPaymentPrimaryTextDisabled = Color(0x42000000),
            aiPaymentSecondary = Color(0x1AFFFFFF),
            aiPaymentSecondaryDisabled = Color(0x1AFFFFFF),
            aiPaymentSecondaryText = Color(0xE6FFFFFF),
            aiPaymentSecondaryTextDisabled = Color(0x42FFFFFF),
            assist = Color(0xFF5C93E5),
            azure = Color(0xFF209DE5),
            azureVariant = Color(0xFF3D98CC),
            background = Color(0xFF000000),
            backgroundElevated = Color(0xFF1E1E1E),
            backgroundElevatedWithCard = Color(0xFF1E1E1E),
            backgroundTop = Color(0xFF333333),
            backgroundWithCard = Color(0xFF000000),
            bar = Color(0xFF1E1E1E),
            blue = Color(0xFF1A8CFF),
            blueVariant = Color(0xFF5C93E5),
            bottomBar = Color(0xFFFAFAFA),
            card = Color(0x1AFFFFFF),
            cardBackground = Color(0x1AFFFFFF),
            cardPressed = Color(0x33FFFFFF),
            container12 = Color(0x33FFFFFF),
            container16 = Color(0x40FFFFFF),
            container4 = Color(0x1AFFFFFF),
            container8 = Color(0x1AFFFFFF),
            containerAzure = Color(0xFF373F42),
            containerBlue = Color(0xFF323739),
            containerCyan = Color(0xFF343E3D),
            containerGreen = Color(0xFF353E36),
            containerMint = Color(0xFF394342),
            containerOrange = Color(0xFF39332C),
            containerPurple = Color(0xFF3A3540),
            containerRed = Color(0xFF3A3030),
            containerSolid = Color(0xFF262626),
            containerTheme = Color(0xFF1A8CFF),
            containerThemeHalftone = Color(0x401A8CFF),
            containerViolet = Color(0xFF3A3A43),
            containerYellow = Color(0xFF373530),
            controls = Color(0x40FFFFFF),
            cyan = Color(0xFF25A9B8),
            cyanVariant = Color(0xFF329DA8),
            disable = Color(0x4D1A8CFF),
            disabledNeutral = Color(0x4DFFFFFF),
            divider = Color(0x33FFFFFF),
            error = Color(0xFFFF6C61),
            errorDisabled = Color(0x4DDB382C),
            errorTextBg = Color(0xFFEA3939),
            fillSolid = Color(0xFF262626),
            fillThin = Color(0x14FFFFFF),
            focus = Color(0x331A8CFF),
            focusOutline = Color(0x665C9DFF),
            green = Color(0xFF24B232),
            greenVariant = Color(0xFF43A84E),
            hintNeutral = Color(0x4DFFFFFF),
            hover = Color(0x26FFFFFF),
            labelOnColor = Color(0xFFFFFFFF),
            labelPrimary = Color(0xE6FFFFFF),
            labelPrimaryVariant = Color(0xB8FFFFFF),
            labelQuaternary = Color(0x26FFFFFF),
            labelSecondary = Color(0x8AFFFFFF),
            labelSecondaryVariant = Color(0x66FFFFFF),
            labelTertiary = Color(0x4DFFFFFF),
            labelTheme = Color(0xFF1A8CFF),
            mask = Color(0x99000000),
            mint = Color(0xFF1AB883),
            mintVariant = Color(0xFF32A881),
            onPrimary = Color(0xFFFFFFFF),
            orange = Color(0xFFF08222),
            orangeVariant = Color(0xFFCC7F3D),
            press = Color(0x33FFFFFF),
            pressBackground = Color(0x26FFFFFF),
            primary = Color(0xFF1A8CFF),
            primaryNeutral = Color(0xE6FFFFFF),
            primaryText = Color(0xFF5C9DFF),
            primaryTextOnPopup = Color(0xFF5C9DFF),
            purple = Color(0xFFAC33FF),
            purpleVariant = Color(0xFFA466CC),
            quarternaryNeutral = Color(0x26FFFFFF),
            red = Color(0xFFEB493D),
            redVariant = Color(0xFFCC615A),
            ripplePressBackground = Color(0x80FFFFFF),
            secondNeutral = Color(0x8AFFFFFF),
            secondary = Color(0x401A8CFF),
            success = Color(0xFF24B232),
            surface = Color(0xFF1E1E1E),
            surfaceTop = Color(0xFF333333),
            surfaceWithCard = Color(0xFF1E1E1E),
            tips = Color(0xFF1A8CFF),
            violet = Color(0xFF7161FF),
            violetVariant = Color(0xFF7E73E5),
            yellow = Color(0xFFE5A100),
            yellowVariant = Color(0xFFC29427),
            couiPrimaryTextColor = Color(0xFFFFFFFF),
        )
    }
}
